name: Publish Workflow

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Check for Version Bump
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'package\.json'; then
            echo "Version bumped in package.json"
            echo "::set-output name=version_bumped::true"
          else
            echo "Version not bumped in package.json"
            echo "::set-output name=version_bumped::false"
          fi

      - name: Create Dist Branch
        if: steps.version_changed.outputs.version_bumped
        run: git checkout dist || git checkout -b dist

      - name: Build and Move Files
        if: steps.version_changed.outputs.version_bumped
        run: |
          pnpm build
          PACKAGE_VERSION=$(jq -r .version package.json)
          mkdir -p "$GITHUB_WORKSPACE/$PACKAGE_VERSION"
          mv schema/* "$GITHUB_WORKSPACE/$PACKAGE_VERSION"

      - name: Commit and Push Changes
        if: steps.version_changed.outputs.version_bumped
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Add build files for version $PACKAGE_VERSION"
          git fetch origin
          git push --force origin dist

      - name: Create Release and Tag
        if: steps.version_changed.outputs.version_bumped
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version_changed.outputs.version_bumped }}
          release_name: Release ${{ steps.version_changed.outputs.version_bumped }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
