name: Publish Workflow

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Check if version has been updated
        id: version_check
        uses: EndBug/version-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        if: steps.version_check.outputs.changed
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'

      - name: Install pnpm
        if: steps.version_check.outputs.changed
        run: npm install -g pnpm

      - name: Install Dependencies
        if: steps.version_check.outputs.changed  
        run: pnpm install

      - name: Checkout Dist Branch
        if: steps.version_check.outputs.changed
        run: |
          git checkout -b dist
          git pull origin dist --ff-only

      - name: Build and Move Files
        if: steps.version_check.outputs.changed
        run: |
          pnpm build
          mkdir -p "$GITHUB_WORKSPACE/${{ steps.version_check.output.version }}"
          mv schema/* "$GITHUB_WORKSPACE/${{ steps.version_check.output.version }}"

      - name: Commit and Push Changes
        if: steps.version_check.outputs.changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Add build files for version ${{ steps.version_check.output.version }}"
          git push origin dist

      - name: Create Release and Tag
        if: steps.version_check.outputs.changed
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.version_check.output.version }}
          release_name: ${{ steps.version_check.output.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
